fix: `--limit` options type
lablup/backend.ai pull request #1003
Opened 2023-01-27 02:39 UTC by Yaminyam

close #1001 

Changed the value of --limit option to recognize as int type that was being treated as str.

2023-01-29 07:42 UTC, fregataa requested changes
the list cmd of agent, keypair, storage, session, user, vfolder have `--limit` option and only session's list have `int` type on the option.
please check all of those commands, not only user's cmd.

2023-01-31 02:07 UTC, kyujin-cho requested changes

2023-01-31 02:07 UTC, kyujin-cho commented on changes/1003.fix.md
> +Changed the value of `--limit` option to recognize as int type that was being treated as str.
We're changing "type" of `--limit` option, not "value". 😉
```suggestion
Fix `--limit` option being treated as `str` instead of `int`
```

2023-01-31 02:17 UTC, kyujin-cho approved these changes

2023-01-31 02:17 UTC, merged