feat: configurable-webserver-password-checkers
lablup/backend.ai pull request #1008
Opened 2023-01-28 11:03 UTC by adrysn

- feat: add `PasswordLengthChecker` and config option
- refactor: password checker options are now dictionary
- Revert update_password_handler. Will be handled by manager plugin.
- fix: flake8 error

2023-01-29 11:47 UTC, fregataa requested changes

2023-01-29 11:47 UTC, fregataa commented on src/ai/backend/manager/api/auth.py
> +    raise AuthorizationFailed("Test Error")
Please remove test err!

2023-01-29 14:58 UTC, adrysn commented on src/ai/backend/manager/api/auth.py
> +    raise AuthorizationFailed("Test Error")
Oops... I removed the code. Thanks.

2023-01-30 05:50 UTC, kyujin-cho requested changes

2023-01-30 05:50 UTC, kyujin-cho commented on src/ai/backend/web/auth.py
> +        api_session.aiohttp_session.headers.update(_headers)
Is there a specific reason for removing fallback logic of value of "X-Forwarded-For"?

2023-02-01 01:32 UTC, kyujin-cho approved these changes

2023-02-01 01:32 UTC, kyujin-cho commented on src/ai/backend/web/auth.py
> +        api_session.aiohttp_session.headers.update(_headers)
My mistake. The fallback logic is covered in `get_client_ip()`.

2023-02-01 01:32 UTC, merged