feat: Enable lark to query multiple rows from joined tables
lablup/backend.ai pull request #1022
Opened 2023-02-07 08:53 UTC by fregataa

2023-02-07 08:54 UTC, fregataa commented on src/ai/backend/manager/models/minilang/ordering.py
> +                    col = self._sa_table.c[self._column_map[col_name]]
This branch seems not good.
Should I change all `_queryorder_colmap` from `Mapping[str, str]` into `Mapping[str, tuple]`?

2023-02-15 08:20 UTC, achimnol reviewed
Could we use `array_agg` instead of `string_agg` so that we could return the multiple belonging projects as a structured list?

2023-02-15 16:51 UTC, fregataa commented
> Could we use `array_agg` instead of `string_agg` so that we could return the multiple belonging projects as a structured list?

I add `array_agg` function. thank you for your review!

2023-02-25 07:18 UTC, achimnol requested changes
Please update the test case!

2023-06-30 08:38 UTC, achimnol approved these changes

2023-06-30 08:40 UTC, merged