Fix: update vfolder clone status by id rather name
lablup/backend.ai pull request #1145
Opened 2023-03-08 13:17 UTC by fregataa

vfolder clone API has updated the status of cloned vfolder by name not id.
This PR fix the bug and uses `execute_with_retry` function to insert and update vfolder table.

2023-03-09 04:02 UTC, kyujin-cho requested changes

2023-03-09 04:02 UTC, kyujin-cho commented on src/ai/backend/manager/api/vfolder.py
> +    task_id, trg_folder_id = await initiate_vfolder_clone(
Let's write variable name as `target` instead of `trg` to enhance readability. 
```suggestion
    task_id, target_folder_id = await initiate_vfolder_clone(
```

2023-03-09 04:02 UTC, kyujin-cho commented on src/ai/backend/manager/models/vfolder.py
> +    trg_host: str
Same here. 
```suggestion
    target_vfolder_name: str
    target_host: str
```

2023-03-09 04:02 UTC, kyujin-cho commented on src/ai/backend/manager/models/vfolder.py
> +    trg_folder_id = uuid.uuid4()
Also here. 
```suggestion
    target_proxy, target_volume = storage_manager.split_host(vfolder_info.trg_host)
    src_proxy, src_volume = storage_manager.split_host(vfolder_info.src_host)

    # Generate the ID of the destination vfolder.
    # TODO: If we refactor to use ORM, the folder ID will be created from the database by inserting
    #       the actual object (with RETURNING clause).  In that case, we need to temporarily
    #       mark the object to be "unusable-yet" until the storage proxy craetes the destination
    #       vfolder.  After done, we need to make another transaction to clear the unusable state.
    target_folder_id = uuid.uuid4()
```

2023-03-09 04:59 UTC, achimnol commented
Also please add the news fragment!

2023-03-10 01:53 UTC, kyujin-cho approved these changes

2023-03-10 01:54 UTC, merged