feat: rewrite `cuda-mock` plugin to support mocking arbitrary accelerator
lablup/backend.ai pull request #1158
Opened 2023-03-11 04:41 UTC by kyujin-cho

This PR adds support to mock any kind of accelerators by updating `cuda-mock` implementations to let user configure slot name of mocked accelerator plugin. Consult `configs/accelerator/mock-accelerator.toml` for more information.

2023-03-11 04:44 UTC, kyujin-cho commented
Notice: once this PR is merged, every users currently utilizing `cuda-mock` plugin need to rewrite their `cuda-mock.toml` config file to match new format.

2023-03-12 01:43 UTC, achimnol approved these changes
LGTM!

2023-03-12 01:43 UTC, achimnol commented
This should have a changelog, though.

2023-03-12 01:49 UTC, achimnol commented
I'll add some documentation for this.

2023-03-14 08:19 UTC, achimnol commented
TODO: rewrite plugin to recognize the new subtype-aware formatting config / update docs accordingly

2023-03-30 06:39 UTC, achimnol requested changes
Need to rewrite the plugin to load per-subtype (e.g., `.devices` or `.shares`) format information instead of the global ones.

2023-04-18 06:49 UTC, achimnol reviewed
Added note about just a minor expression. Otherwise, LGTM.

2023-04-18 06:49 UTC, achimnol commented on src/ai/backend/accelerator/mock/plugin.py
> +            log.error("Unimplemented allocation mode: {}", self._mode)
How about just saying "Invalid"? 😉

2023-04-18 07:03 UTC, merged