fix: Add new user grace period to remaining idle time.
lablup/backend.ai pull request #1205
Opened 2023-04-01 04:48 UTC by fregataa

Add new user grace period to remaining idle time of each checker.

2023-04-02 14:55 UTC, adrysn approved these changes
LGTM.

2023-04-03 04:01 UTC, kyujin-cho requested changes

2023-04-03 04:01 UTC, kyujin-cho commented on src/ai/backend/manager/idle.py
> +        grace_period_end: Optional[datetime],
Did it meant to be a keyword parameter? If then please add default value. 
```suggestion
        grace_period_end: Optional[datetime] = None,
```

2023-04-03 04:01 UTC, kyujin-cho commented on src/ai/backend/manager/idle.py
> +                redis_obj, session_id, result if result > 0 else -1
What is the meaning of `-1`?

2023-04-03 06:58 UTC, kyujin-cho approved these changes

2023-04-03 06:58 UTC, merged