Add `agent_id` label to containers
lablup/backend.ai pull request #1266
Opened 2023-05-06 05:10 UTC by fregataa

resolves #875

2023-05-06 08:30 UTC, achimnol requested changes
I think we also need to consider the container's `ai.backend.owner` labels when scanning contaienrs in the agents.

2023-05-06 09:41 UTC, fregataa commented
> I think we also need to consider the container's `ai.backend.owner` labels when scanning contaienrs in the agents.

Should we remove `kernel_registry` or impl a method to sync it by scanning containers?

2023-05-06 10:35 UTC, fregataa commented
> I think we also need to consider the container's `ai.backend.owner` labels when scanning contaienrs in the agents.

When scanning containers, should I sync `kernel_registry` by creating missing kernel object or just skip other's kernel object, or do both?

2023-05-08 08:32 UTC, achimnol approved these changes

2023-05-08 08:35 UTC, merged