fix: skip execution of `pr-number-assign.py` script
lablup/backend.ai pull request #1269
Opened 2023-05-08 09:15 UTC by kyujin-cho

This PR updates `pr-number-assign.py` to prevent update-news-fragments action failing when PR is merged by merge queue. Looks like actions with trigger `workflow_call` is ran on push to `main` branch when PR is merged via merge queue Because of this, the `pr-number-assign.py` will be started with empty string (originated from empty "github.event.pull_request.number" action variable) as an argument, making script to crash. The updated script will now also gracefully terminate with a warning message complaining about missing Pull Request number, making action runner to convince that execution has done without any error.

2023-05-08 11:52 UTC, achimnol commented
It would be better to use GitHub Action's conditional workflow execution syntax.
refs)
https://docs.github.com/en/actions/learn-github-actions/expressions
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

2023-05-09 02:21 UTC, Yaminyam reviewed
Does `timeline-check` need to be triggered with merge_group?

2023-05-14 08:07 UTC, achimnol commented
> Does `timeline-check` need to be triggered with merge_group?

Yes, it is a required check for all merging PRs, unless the PR is marked with "skip:changelog".
But if the PR number and labels are not available in the merge group action, it is fine to skip it.

2023-05-14 08:08 UTC, achimnol requested changes

2023-05-14 08:08 UTC, achimnol commented on scripts/pr-number-assign.py
> +        exit(0)
I think still this should be an explicit failure.

2023-05-15 08:12 UTC, achimnol approved these changes

2023-05-15 08:29 UTC, merged