feat: Impl dummy agent
lablup/backend.ai pull request #1313
Opened 2023-06-01 07:45 UTC by fregataa

resolves #1283

2023-06-07 08:59 UTC, achimnol requested changes
Just some minor requested changes. The overall impl looks fine.

2023-06-07 08:59 UTC, achimnol commented on .gitignore
> +/dummy-agent-config.toml
I'd like to rename this to have the namespace first: `agent.dummy.toml`, with dots as the delimeter to indicate the subcomponent.

2023-06-07 08:59 UTC, achimnol commented on scripts/install-dev.sh
> +  cp configs/agent/sample-dummy-config.toml ./dummy-agent-config.toml
Same here.

2023-06-07 08:59 UTC, achimnol commented on src/ai/backend/agent/dummy/utils.py
How about refactor this as a trafaret (like `manager/config.py` or `agent/config.py`), which converts the config value into a callable that does what `get_delay_from_cfg()` does.

2023-06-07 09:16 UTC, fregataa commented on src/ai/backend/agent/dummy/utils.py
that is nice. I made `Delay` trafaret validator in `agent/dummy/config.py`. thank you!

2023-06-16 03:15 UTC, achimnol requested changes
A minor refactoring please!

2023-06-16 03:15 UTC, achimnol commented on src/ai/backend/agent/dummy/config.py
> +class Delay(t.Trafaret):
Let's move this to `ai.backend.common.validators` like other "trafaret extensions" (`tx`) classes.

2023-06-16 03:24 UTC, achimnol approved these changes

2023-06-16 04:36 UTC, merged