ci: Detect packages that do not have binary files
lablup/backend.ai pull request #1324
Opened 2023-06-09 17:08 UTC by Yaminyam

resolve #1303

2023-06-10 05:07 UTC, achimnol requested changes

2023-06-10 05:07 UTC, achimnol commented on .github/workflows/check-requiredment.yml
> +            | select(any(.artifacts[].url; endswith(".whl")) | not) | .project_name' >> no-exist-binary.txt
* `no-exist-binary.txt` looks like too Konglish...
  Let's rename it to `packages-missing-precompiled-wheels`.

* What if the target package is a pure Python package that provides only the source distribution?

2023-06-12 03:41 UTC, kyujin-cho requested changes

2023-06-12 03:41 UTC, kyujin-cho commented on .github/workflows/check-requiredment.yml
You've meant to represent `requirement`, right?

2023-06-12 03:42 UTC, Yaminyam commented on .github/workflows/check-requiredment.yml
Oh yes my mistake.

2023-06-22 01:10 UTC, merged