fix: add images column to sessions and enable to order or filter by image
lablup/backend.ai pull request #1378
Opened 2023-07-06 05:37 UTC by fregataa

Add `images` column to filter or order by image when list sessions.
`images` column is ARRAY type and the first component of `images` column is main kernel's image.
graphene will return `image` when we query sessions, which is the image of main kernel.

2023-07-06 06:58 UTC, Sujin-Kim1 requested changes
<img width="560" alt="image" src="https://github.com/lablup/backend.ai/assets/28584164/6ffb1296-57c7-4c71-858c-80b5538f7fd5">

@fregataa When I tested, I got this error.

2023-07-11 07:44 UTC, fregataa commented
> <img alt="image" width="560" src="https://user-images.githubusercontent.com/28584164/251369643-6ffb1296-57c7-4c71-858c-80b5538f7fd5.png">
> @fregataa When I tested, I got this error.

updated. please re-review it!

2023-07-14 02:19 UTC, adrysn approved these changes
LGTM.
<img width="589" alt="image" src="https://github.com/lablup/backend.ai/assets/7539358/32c3cbbf-9ea5-4e02-afcd-7466bee55be8">

2023-07-14 02:37 UTC, kyujin-cho approved these changes

2023-07-14 02:44 UTC, merged