fix: Wrong agent picking issue when using multi-node
lablup/backend.ai pull request #1394
Opened 2023-07-13 05:43 UTC by jopemachine

This PR relates to https://github.com/lablup/backend.ai/issues/1384#event-9770189002.

Discussion: https://teams.microsoft.com/l/message/19:3c0acc0825024daeb2211f55c4e7f4aa@thread.skype/1689215390841?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1689215390841&teamName=devops&channelName=Backend.AI%20Talks&createdTime=1689215390841

2023-07-21 06:58 UTC, fregataa commented on src/ai/backend/common/types.py
> +    LEGACY = "legacy"
How about leaving any hint comment for this `LEGACY` strategy?

2023-07-22 06:24 UTC, fregataa requested changes
It is great in overall!
I left some comments.

2023-07-22 06:24 UTC, fregataa commented on src/ai/backend/manager/models/scaling_group.py
> +                ),
```suggestion
                t.Key("agent_selection_strategy", default=AgentSelectionStrategy.DISPERSED): tx.Enum(
                    AgentSelectionStrategy
                ),
```

we have [customized Enum trafaret type](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/common/validators.py#L212). Let's use this!

2023-07-22 06:24 UTC, fregataa commented on src/ai/backend/manager/scheduler/drf.py
> +    return comparator
👍

2023-07-24 08:06 UTC, achimnol commented on src/ai/backend/common/types.py
> +    LEGACY = "legacy"
Note: `LEGACY` chooses the largest agent (the sort key is a tuple of resource slots).

Currently there is no explicit slot preference list to create a sort key but only 
moves "strict" less/greater items in the agent list. Let's also add an explicit configuration like [the agent's `allocation-order` config](https://github.com/lablup/backend.ai/blob/6da46120/configs/agent/sample.toml#L261) and [the sorting mechanism](https://github.com/lablup/backend.ai/blob/6da46120/src/ai/backend/agent/agent.py#L1671-L1707).

2023-08-02 16:30 UTC, fregataa commented on src/ai/backend/manager/scheduler/drf.py
> +) -> list[int]:
I guess the return value of this function is a list of resource remaining or available in total.
Then, the return value should be `list[Decimal]` type. Please let me know whether I guess it correctly!

2023-08-03 02:13 UTC, jopemachine commented on src/ai/backend/manager/scheduler/drf.py
> +) -> list[int]:
Thanks for the correction! 
I think using Decimal would be more proper here.
and I checked the ResourcePolicy types keys like `cpu`, `mem` are Decimal.
So, let's change these return types using `Decimal`

2023-08-03 05:57 UTC, achimnol requested changes
Almost there!

2023-08-03 05:57 UTC, achimnol commented on src/ai/backend/manager/scheduler/fifo.py
> +        first = requested_slot_key.split(".")[0]
Conventionally we have called this string as `device_name`.
Let's follow the same convention.
(ref: https://github.com/lablup/backend.ai/blob/08c81ca48/src/ai/backend/agent/alloc_map.py#L127)

2023-08-03 05:57 UTC, achimnol commented on src/ai/backend/manager/scheduler/drf.py
> +        first = requested_slot_key.split(".")[0]
Same here!

2023-08-16 02:56 UTC, achimnol requested changes
When I tried to run a hello-world with this PR, the manager crashes:
<img width="1557" alt="image" src="https://github.com/lablup/backend.ai/assets/555156/8cc3bbea-375c-4b0e-a9cc-23d51c2021c5">

I see there is no dastabase migrations required.
Could we make a fallback for existing setups to continue working after applying this PR?

2023-08-22 02:10 UTC, jopemachine commented
> When I tried to run a hello-world with this PR, the manager crashes: <img alt="image" width="1557" src="https://user-images.githubusercontent.com/555156/260888446-8cc3bbea-375c-4b0e-a9cc-23d51c2021c5.png">
> 
> I see there are no dastabase migrations required. Could we make a fallback for existing setups to continue working after applying this PR?

I'm sorry for forgetting to add `agent-selection-resource-priority` to the `config.py`.

I think the default value of the `agent-selection-resource-priority` specified in the `config.py` will handle in case of  `agent-selection-resource-priority` is missing (default fallback)

2023-08-23 08:25 UTC, achimnol commented
> I think the default value of the `agent-selection-resource-priority` specified in the `config.py` will handle in case of `agent-selection-resource-priority` is missing (default fallback)

Yes, that's correct!

2023-08-23 08:27 UTC, achimnol approved these changes

2023-08-23 08:32 UTC, merged