fix: delete vfolder conditions of checking host while creating/cloneing vfolders
lablup/backend.ai pull request #1407
Opened 2023-07-21 06:18 UTC by NayeonKeum

resolves: #1398 

**Done**

Originally `when creating/cloneing vfolders` we `checked if two conditions are the same`, it's `name` and `host`.

To block creating/cloning vfolders with duplicate names even on different hosts, I `deleted a condition that checked whether if the host is same or not`. (Only conditions of checking names remains).

This will gradually make it impossible to create vfolder with names, whatever the host is.

**Test**

I executed postgres querys directly into it's docker container and checked if this works.

2023-07-22 06:18 UTC, fregataa approved these changes
LGTM!
Let's wait for other's review

2023-07-24 08:08 UTC, achimnol requested changes
Just a typo. :wink:

2023-07-24 08:08 UTC, achimnol commented on changes/1398.fix.md
> +Prevent creating/cloneing vfolders with duplicate names on different hosts by deleting conditions checking host.
```suggestion
Prevent creating/cloning vfolders with duplicate names on different hosts by deleting conditions checking host.
```

2023-07-24 08:36 UTC, achimnol approved these changes

2023-07-24 08:39 UTC, merged