refactor: Update URL parsing and validation in the `URL` class
lablup/backend.ai pull request #1432
Opened 2023-07-28 05:39 UTC by kimjinmyeong

As a result of this [PR](https://github.com/lablup/backend.ai-webui/pull/1806), regular expressions are no longer used for URL validation. 
So, I updated to reflect this change in URL validation at backend.ai manager.

**Improvement**
- Modified the URL scheme validation to avoid using regular expressions.
- Exception handling codes have been modified to catch possible exceptions raised by the yarl library
The yarl library provides appropriate error messages for each exception. ([yarl GitHub repo](https://github.com/aio-libs/yarl/blob/1f94e1a7833a27203d63f8618d01d4d4fa2d3520/yarl/_url.py))

2023-08-01 04:34 UTC, fregataa reviewed
Good! I left one comment

2023-08-01 04:34 UTC, fregataa commented on src/ai/backend/common/validators.py
> +            self._failure(f"{e}", value=value)
```suggestion
            self._failure(repr(e), value=value)
```
this would be better

2023-08-02 16:29 UTC, achimnol requested changes

2023-08-02 16:29 UTC, achimnol commented on src/ai/backend/common/validators.py
> +        except Exception as e:
Let's narrow down this to `ValueError`.
See https://github.com/aio-libs/yarl/blob/master/yarl/_url.py

2023-08-03 03:45 UTC, achimnol approved these changes

2023-08-03 04:04 UTC, merged