add: `max_count_for_pre_opened_port` setting to webserver config
lablup/backend.ai pull request #1477
Opened 2023-08-14 05:04 UTC by Sujin-Kim1

resolves https://github.com/lablup/giftbox/issues/482
related: https://github.com/lablup/backend.ai-webui/pull/1843

2023-08-14 10:09 UTC, kyujin-cho requested changes
Let's unify the terminology to `Preopen Ports`, instead of `Pre-open ports`, `Pre opened ports` or `Preopened ports`.

2023-08-16 12:42 UTC, kyujin-cho requested changes

2023-08-16 12:42 UTC, kyujin-cho commented on src/ai/backend/web/templates/config.toml.j2
> +{% toml_field "maxCountForPreOpenedPort" config["session"]["max_count_for_preopen_ports"] %}
Perhaps changes from [here](https://github.com/lablup/backend.ai-webui/pull/1861/files#diff-afc7c81ccfa8595a7b1c9b0199bc353d01316fd518c5295cdfbe8ebcc1556ee8R29) are not reflected at this PR?

2023-08-16 16:28 UTC, agatha197 commented on src/ai/backend/web/templates/config.toml.j2
> +{% toml_field "maxCountForPreOpenedPort" config["session"]["max_count_for_preopen_ports"] %}
oops you are right

2023-08-20 06:59 UTC, kyujin-cho approved these changes

2023-08-20 07:02 UTC, merged