fix: replace `kernels.role` to `sessions.session_type`
lablup/backend.ai pull request #1587
Opened 2023-09-19 16:49 UTC by fregataa

According to the predefined concept, the kernel should not have a `role` field and the `session_type` of the session should imply this instead.
https://sorna--1468.org.readthedocs.build/en/1468/concepts/computing.html#session-types

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version

2024-05-03 09:35 UTC, achimnol requested changes
Let's migrate the postgres enum to use the new `manager.models.base.StrEnumType` to avoid boilerplates when adding/removing enum items in the postgres schema. Refer #1936.

2024-08-21 06:18 UTC, achimnol requested changes

2024-08-21 06:18 UTC, achimnol commented on src/ai/backend/manager/models/kernel.py
> +}
Why is this needed if we migrate to `enum.StrEnum`?

2024-08-21 06:18 UTC, achimnol commented on src/ai/backend/manager/models/session.py
> +PRIVATE_SESSION_TYPES = (SessionTypes.SYSTEM,)
As a follow-up work, this should be refactored to handle "special type" sessions like SFTP containers which allow direct access without AppProxy.

2024-08-21 07:01 UTC, fregataa commented on src/ai/backend/manager/models/kernel.py
> +}
I don't get the reason or advantage of using `enum.StrEnum` here rather than `Mapping`.
As I understand, enum is to represent type, not to map data.

2024-08-21 15:20 UTC, achimnol commented on src/ai/backend/manager/models/kernel.py
> +}
`StrEnum` fields are string values that are also bidirectionally convertible from/to the Enum instances. There is **no need** to have an extraneous mapping from StrEnum instances to str values **at all.**

2024-08-21 15:22 UTC, achimnol commented on src/ai/backend/manager/models/kernel.py
> +}
Read the manual: https://docs.python.org/3/library/enum.html#enum.StrEnum

2024-08-21 15:28 UTC, achimnol commented on src/ai/backend/manager/models/kernel.py
> +}
Ah, this mapping is for:
<img width="587" alt="image" src="https://github.com/user-attachments/assets/92beedd3-dab2-46f0-b5ea-3d49fb97eb20">

It seems to be an equivalent but unnecessarily reversed logical expression.
It should be a mapping from the label value to a `SessionTypes` value and compared with `session_type`.

2024-08-21 15:42 UTC, achimnol commented on src/ai/backend/manager/models/kernel.py
> +}
We also need to consider the cases when images have multiple roles.

2024-09-20 16:57 UTC, achimnol commented
We need to do a follow-up fix for https://github.com/lablup/backend.ai/issues/2746#issuecomment-2364138900 after merging the stack including #2848.

2024-09-20 16:58 UTC, achimnol approved these changes

2024-09-20 17:03 UTC, merged