feature: revamp dummy agent to have compute plugins indivisually
lablup/backend.ai pull request #1597
Opened 2023-09-25 08:36 UTC by fregataa

Let dummy agents to have compute plugins indivisually.

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version

2023-10-30 06:14 UTC, kyujin-cho commented
Perhaps we can find a way to integrate our mock accelerator plugin with dummy agent.

2024-04-16 13:48 UTC, achimnol requested changes

2024-04-16 13:48 UTC, achimnol commented on agent1.toml
Please remove this file if not intended to include.

2024-04-16 13:48 UTC, achimnol commented on src/ai/backend/agent/dummy/config.py
> +            ),  # Key: a string of image canonical, Value: hash. it can be a random string.
Please include the concrete example of this value structure in the sample toml.

2024-04-16 13:48 UTC, achimnol commented on configs/agent/sample.toml
> +# missing = []
`sample-dummy-config.toml` has
```toml
[agent.image.already-have]
'cr.backend.ai/multiarch/python:3.9-ubuntu20.04' = ''
```
and it breaks up the starting of the agent if I copy `sample-dummy-config.toml` to `agent.toml`.
I think it would be better to have an example configuration that can be copied and used out of the box.

```
> ./backend.ai ag start-server --debug
ConfigurationError: Validation of agent local config has failed:
{'agent': {'image': {'already-have': {0: 'value should be None',
                                      1: 'value is not a dict'}},
           'intrinsic': 'is required',
           'resource': 'resource is not allowed key'}}
Aborted!%
```

Please correct the sample if it needs to be updated.

2024-06-14 03:16 UTC, jopemachine commented
@fregataa Dynamically generating multiple `agent.toml` files for running multiple agents could be a cumbersome task.

I think it would be convenient if a single `agent.toml` file could be used to run multiple agents by enabling the necessary values for each agent to be overridden with environment variables.
(`rpc-listen-addr`, `agent-sock-port`, `id` and `pid-file`.)

What do you think about it?

2025-05-28 08:35 UTC, closed without merging