fix: Change status_history from map to list
lablup/backend.ai pull request #1662
Opened 2023-10-27 05:44 UTC by jopemachine

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Documentation
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to demonstrate the difference of before/after

Related: https://github.com/lablup/backend.ai/pull/1116

2023-11-03 03:11 UTC, jopemachine commented
Tested manually.

<img width="1727" alt="스크린샷 2023-11-03 오후 12 10 39" src="https://github.com/lablup/backend.ai/assets/18283033/f89dd144-58fb-4cab-8174-7dec00021f2b">

2024-05-03 01:41 UTC, achimnol commented
We also need to update clients using the session resource usage API handler's `status_history` field at:
https://github.com/lablup/backend.ai/blob/e77c4a3cd79246541746fca5336a10261d7dc00b/src/ai/backend/manager/api/resource.py#L466
as this does not go through the GraphQL's backward-compatible field generation.

2024-05-03 08:32 UTC, achimnol requested changes

2024-05-03 08:32 UTC, achimnol commented on tests/manager/models/test_utils.py
I think it would be better to preserve the `sql_json_merge()` utility and its test case, although it is not used in elsewhere.
Of course, as the `status_history` column no longer uses this function, we need to add a temporary, minimal table to accommodate a sample json column.

Let's split this part as a separate PR (using the graphite stack).

2024-05-03 08:32 UTC, achimnol commented on src/ai/backend/manager/models/session.py
> +    status_history_log = graphene.JSONString(description="Added in 24.09.0")
Referring [our internal document](https://lablup.sharepoint.com/:fl:/g/contentstorage/CSP_93a3ec6b-3a47-4174-aba8-e022f64d2e6a/EUnXwjFPLWxJhso05OMe8jUB404OyCc_Vpm8hOremhVvKA?e=9C3ACs&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF85M2EzZWM2Yi0zYTQ3LTQxNzQtYWJhOC1lMDIyZjY0ZDJlNmEmZD1iJTIxYS15amswYzZkRUdycU9BaTlrMHVhcnVadTBHN1ZEdEZwem9aRi1qaV91OFdsV0h0XzlhY1RyVEJBWHg0aDFZZiZmPTAxSzRWMkRLU0oyN0JEQ1RaTk5SRVlOU1JVNFRSUjU0UlYmYz0lMkYmYT1Mb29wQXBwJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHhzWVdKc2RYQXVjMmhoY21Wd2IybHVkQzVqYjIxOFlpRmhMWGxxYXpCak5tUkZSM0p4VDBGcE9Xc3dkV0Z5ZFZwMU1FYzNWa1IwUm5CNmIxcEdMV3BwWDNVNFYyeFhTSFJmT1dGalZISlVRa0ZZZURSb01WbG1mREF4U3pSV01rUkxWVkpLVFVSTlUwSkxSbGRXUWpOSVZrZEpUVFZMVmtsU1RrVSUzRCUyMiUyQyUyMmklMjIlM0ElMjI4MTJhZTI0OS1lOTA0LTQ4YjEtOGQ1ZC04OWIxZjc0ZjAyMTQlMjIlN0Q%3D), add the `deprecation_reason` argument to the `status_history` field.

2024-05-03 08:32 UTC, achimnol commented on changes/1662.fix.md
> +Replace `status_history`'s type `map` with `list`
```suggestion
Change the type of `status_history` from a mapping of status and timestamps to a list of log entries containing status and timestamps, to preserve timestamps when revisiting session/kernel statuses (e.g., after session restarts).
```

2024-05-07 02:11 UTC, jopemachine commented on tests/manager/models/test_utils.py
This PR was created before the introduction of Graphite, so it is set to target this PR instead of the main branch. It's possible to create a new PR and stack it, but in cases like PR 1662, it's set this way to include comments and reviews. If a new PR needs to be created, please let me know and I will create a new one.

2024-05-07 08:20 UTC, closed without merging