refactor: change regex of project to allow unicode except any whitespace
lablup/backend.ai pull request #1663
Opened 2023-10-27 06:46 UTC by lizable

This PR resolves #1658.
Before this PR every client-side got "400 Bad Request" error, which is originated from regex that only allows alphanumeric characters,`-`(hyphen) and `_`(underscore). 
After applying this PR will allow unicode characters, such as Korean(e.g. "프로젝트"), But not allowing any whitespaces.

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [x] Mention to the original issue
- [ ] Documentation
- [x] API server-client counterparts (e.g., manager API -> client SDK)
- [x] Test case(s) to demonstrate the difference of before/after

### Screenshot(s)
Before
<img width="1423" alt="Screenshot 2023-10-27 at 3 45 29 PM" src="https://github.com/lablup/backend.ai/assets/46954439/35bfcd05-40b8-4393-9281-70378db98ddc">

After
<img width="1423" alt="Screenshot 2023-10-27 at 3 33 27 PM" src="https://github.com/lablup/backend.ai/assets/46954439/e5c0fff5-2df5-409a-ac0d-3ced50813600">

2023-10-27 07:32 UTC, achimnol requested changes
* We need to add a `TypeDecorator` subclass (in the `manager.models.base` module) for database columns to enforce slug formats, with a new option `allow_unicode` to `common.validators.Slug`.
* Remove `_rx_slug` in the `manager.models.group` module. It should have been refactored and removed.
* Let's add unit tests to demonstrate what examples are accepted or denied.
* The regular expression should use `\w` (e.g., character class as `[-\w]`). Refer the docs. Fortunately, the unicode mode is the default in Python 3. What we want is to allow "word" characters while still disallowing non-whitespace special characters other than the underscore and hyphen.
<img width="821" alt="image" src="https://github.com/lablup/backend.ai/assets/555156/02c4cb99-3e5c-4606-a367-1b07593c9a75">

2024-05-03 09:40 UTC, achimnol requested changes

2024-05-03 09:40 UTC, achimnol commented on src/ai/backend/manager/models/domain.py
> +# _rx_slug = re.compile(r"^[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$")
Please remove commented out codes.

2024-05-03 09:40 UTC, achimnol commented on src/ai/backend/manager/models/group.py
> +# _rx_slug = re.compile(r"^[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$")
Same in this file.

2024-05-03 09:40 UTC, achimnol commented on src/ai/backend/manager/models/base.py
> +        self._rx_slug = re.compile(r"^[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$")
How about using the `\w` pattern in place of `[a-zA-Z0-9]` and setting `re.ASCII` flag as the inverse of `allow_unicode`?

2024-05-09 07:52 UTC, lizable reviewed
LGTM.

2024-07-18 06:02 UTC, achimnol commented
Rewrote the implementation and test cases, to handle variable-length negative lookbehind patterns and forbid consecutive occurrences in the middle as a serial invocation of regex pattern matching.

- Allow alpha-numeric chars (including unicode alphabets like Hangul).
- Allow hyphen, underscore, space, and dot in the middle, _only when_ they appear as a single char between alpha-numeric chars.
- Disallow hyphen, underscore, space, and dot to appear in the head/tail.

Now `manager.models.base.SlugType` and `common.validators.Slug` accepts three options to control the behavior: `allow_dot`, `allow_space`, `allow_unicode`.
Hyphen and underscore are always allowed regardless of the options.

**Difference to the prior implementation:** It now forbids the values beginning with a single dot. (e.g., `".abc"` was allowed but it's not rejected.)

2024-07-18 06:03 UTC, achimnol approved these changes

2024-07-18 06:23 UTC, merged