feat: Allows explicit `null` and empty string for ContainerRegistry
lablup/backend.ai pull request #1670
Opened 2023-10-30 07:26 UTC by rapsealk

This PR is a follow-up of #1471 

This PR enhances GraphQL mutations for ContainerRegistry, by allowing explicit `null` and empty string.

**Checklist:** (if applicable)

- [x] Milestone metadata specifying the target backport version
- [x] Mention to the original issue
- [ ] Documentation
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [x] Test case(s) to demonstrate the difference of before/after

2023-10-30 15:14 UTC, achimnol commented
We should use the explicitly distinguished `undefined` and `null` introduced in Graphene 3.3 after merging #1632, by refactoring `set_if_set()` in all places.

2023-11-02 09:34 UTC, yomybaby approved these changes
LGTM

2023-11-02 15:21 UTC, achimnol requested changes

2023-11-02 15:21 UTC, achimnol commented on .github/workflows/default.yml
> +        docker-compose -f docker-compose.halfstack-main.yml run -d --service-ports backendai-half-etcd
This should be removed and replaced with the `ai.backend.testutils.bootstrap.etcd_container` fixture to keep it parallelization-safe when running `pants test`. Please refer other use cases.

2023-11-03 03:29 UTC, achimnol requested changes

2023-11-03 03:29 UTC, achimnol commented on tests/manager/models/test_etcd.py
> +        "password": "*****",
"*****" is defined as a constant at `ai.backend.manager.defs.PASSWORD_PLACEHOLDER`.
Let's use it.

2023-11-03 03:29 UTC, achimnol commented on tests/manager/models/test_etcd.py
> +    assert container_registry["config"]["password"] == "*****"
Also does this test case reveal that the password is actually set as an empty string? I think we need to directly access the etcd to validate the fact.

2023-11-03 05:12 UTC, achimnol approved these changes

2023-11-03 05:16 UTC, merged