fix: infinite loop when malformed symbolic link exists in container
lablup/backend.ai pull request #1673
Opened 2023-10-31 03:47 UTC by jopemachine

If you create a symlink pointing to yourself in a container and then access it, you will get an infinite loop error like below. (the symlink named 'abc' which could be created by `ln -s abc abc`)

```
work@main1[tzB9zs8e-session]:~$ ls -la
total 64
drwxr-xr-x 8 work work 4096 Oct 31 00:39 .
drwxr-xr-x 1 root root 4096 Oct 31 00:37 ..
-rw-rw-r-- 1 work work  147 Oct 31 00:37 .bash_profile
-rw-rw-r-- 1 work work  249 Oct 31 00:37 .bashrc
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .cache
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .config
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .ipython
drwxrwxr-x 3 work work 4096 Oct 31 00:37 .jupyter
drwxr-xr-x 3 work work 4096 Oct 31 00:37 .local
-rw-r--r-- 1 root root   48 Oct 31 00:37 .password
drwx------ 2 work work 4096 Oct 31 00:37 .ssh
-rw-rw-r-- 1 work work 2195 Oct 31 00:37 .tmux.conf
-rw-rw-r-- 1 work work  501 Oct 31 00:37 .vimrc
-rw-rw-r-- 1 work work  472 Oct 31 00:37 .zshrc
-rw-rw-r-- 1 work work  540 Oct 27 00:55 DO_NOT_STORE_PERSISTENT_FILES_HERE.md
lrwxrwxrwx 1 work work    3 Oct 31 00:39 abc -> abc
-rw------- 1 work work 1675 Oct 31 00:37 id_container
work@main1[tzB9zs8e-session]:~$ logout
Connection to localhost closed.

❯ ./backend.ai session ls tzB9zs8e-session
✗ Traceback (most recent call last):
    File "<string>", line 9, in <module>
  OSError: [Errno 40] Too many levels of symbolic links: '/home/work/abc'
```

This PR fixes this by calling the stat for the symlink itself instead of the original file.

```
❯ ./backend.ai session ls zMgkgFXk-session
✓ Retrived.
File name                              Size       Modified              Mode
-------------------------------------  ---------  --------------------  ----------
id_container                           1.6 KiB    Oct 31 2023 03:35:06  -rw-------
.jupyter                               4.0 KiB    Oct 31 2023 03:35:05  drwxrwxr-x
.bash_history                          21 Bytes   Oct 31 2023 03:45:33  -rw-------
.cache                                 4.0 KiB    Oct 31 2023 03:35:07  drwxr-xr-x
.password                              59 Bytes   Oct 31 2023 03:35:05  -rw-r--r--
.config                                4.0 KiB    Oct 31 2023 03:35:07  drwxr-xr-x
DO_NOT_STORE_PERSISTENT_FILES_HERE.md  540 Bytes  Oct 27 2023 00:55:30  -rw-rw-r--
.vimrc                                 501 Bytes  Oct 31 2023 03:35:05  -rw-rw-r--
abc                                    3 Bytes    Oct 31 2023 03:45:30  lrwxrwxrwx
.bashrc                                249 Bytes  Oct 31 2023 03:35:05  -rw-rw-r--
.zshrc                                 472 Bytes  Oct 31 2023 03:35:05  -rw-rw-r--
.bash_profile                          147 Bytes  Oct 31 2023 03:35:05  -rw-rw-r--
.local                                 4.0 KiB    Oct 31 2023 03:35:06  drwxr-xr-x
.ipython                               4.0 KiB    Oct 31 2023 03:35:06  drwxr-xr-x
.tmux.conf                             2.1 KiB    Oct 31 2023 03:35:05  -rw-rw-r--
.ssh                                   4.0 KiB    Oct 31 2023 03:35:06  drwx------

```

Tested manually.

2023-11-10 05:01 UTC, achimnol requested changes

2023-11-10 05:01 UTC, achimnol commented on src/ai/backend/agent/docker/kernel.py
> +                fstat = f.stat()
According to [the official docs](https://docs.python.org/3.12/library/os.html#os.DirEntry.stat), we can simpy write this:
```suggestion
            fstat = f.stat(follow_symlinks=False)
```

2023-11-10 05:01 UTC, achimnol commented on src/ai/backend/agent/kubernetes/kernel.py
> +                fstat = f.stat()
Same here.
```suggestion
            fstat = f.stat(follow_symlinks=False)
```

2023-11-12 05:31 UTC, jopemachine commented
I confirmed that the modified source code works as intended.

```
backend.ai  🍣 fix/symbolic-eloop2 [$!?] 🐍 v3.11.4
🕙 14:25:11 ❯ ./backend.ai session ls oSzXzRbS-session
✗ Traceback (most recent call last):
    File "<string>", line 9, in <module>
  OSError: [Errno 40] Too many levels of symbolic links: '/home/work/abc'


backend.ai  🍣 fix/symbolic-eloop2 [$!?] 🐍 v3.11.4
🕙 14:26:38 ✖  ./backend.ai session ls oSzXzRbS-session
✓ Retrived.
File name                              Size       Modified              Mode
-------------------------------------  ---------  --------------------  ----------
.config                                96 Bytes   Nov 12 2023 14:21:09  drwxr-xr-x
abc                                    3 Bytes    Nov 12 2023 14:25:04  lrwxr-xr-x
id_container                           1.6 KiB    Nov 12 2023 14:21:09  -rw-------
.tmux.conf                             2.1 KiB    Nov 12 2023 14:21:08  -rw-r--r--
.bashrc                                249 Bytes  Nov 12 2023 14:21:08  -rw-r--r--
.zshrc                                 472 Bytes  Nov 12 2023 14:21:08  -rw-r--r--
DO_NOT_STORE_PERSISTENT_FILES_HERE.md  540 Bytes  Aug 03 2023 10:27:56  -rw-r--r--
.local                                 96 Bytes   Nov 12 2023 14:21:09  drwxr-xr-x
.ipython                               96 Bytes   Nov 12 2023 14:21:09  drwxr-xr-x
.password                              58 Bytes   Nov 12 2023 14:21:08  -rw-r--r--
.ssh                                   96 Bytes   Nov 12 2023 14:21:09  drwx------
.vimrc                                 501 Bytes  Nov 12 2023 14:21:08  -rw-r--r--
.jupyter                               96 Bytes   Nov 12 2023 14:21:08  drwxr-xr-x
.bash_profile                          147 Bytes  Nov 12 2023 14:21:08  -rw-r--r--
.cache                                 96 Bytes   Nov 12 2023 14:21:09  drwxr-xr-x
.bash_history                          88 Bytes   Nov 12 2023 14:25:06  -rw-------
```

2023-11-13 00:56 UTC, sanxiyn approved these changes

2023-11-13 01:02 UTC, merged