feature: Query inode quota by GraphQL
lablup/backend.ai pull request #1800
Opened 2023-12-19 10:24 UTC by fregataa

related to https://github.com/lablup/giftbox/issues/62#event-11286108235

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-05-24 04:00 UTC, agatha197 requested changes
Please add version compatibility

2024-05-28 02:26 UTC, agatha197 commented
when I called `set_quota_scope`, I got this error.
<img width="293" alt="image" src="https://github.com/lablup/backend.ai/assets/28584164/72e66587-0732-494c-849f-559bb00cd8fb">
Here are my params.
<img width="508" alt="image" src="https://github.com/lablup/backend.ai/assets/28584164/c754a599-c0c5-45a0-a506-3542c7a28605">
Can you check again? @fregataa 
(Test server: 10.82.230.49)

2024-07-03 00:44 UTC, yomybaby requested changes
Please resolve conflicts.

2024-07-06 09:06 UTC, achimnol requested changes
```
  usage_bytes: BigInt
  usage_count: BigInt
  hard_limit_bytes: BigInt
  hard_limit_inodes: BigInt
```

Why is the last field named `inodes` instead of `count`?

2025-05-28 08:45 UTC, closed without merging