Fix: Pants install directory changed from ~/bin to ~/.local/bin
lablup/backend.ai pull request #1806
Opened 2023-12-22 05:33 UTC by hoyajigi

resolves #1751

due to the [recent changes in pants install script](https://github.com/pantsbuild/setup/pull/144), the install directory of pants changed to ~/.local/bin

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2023-12-27 07:47 UTC, achimnol requested changes
Thanks for catching this!
Please add a news fragment file (check out other merged PRs about how to name & write it).

2023-12-28 02:22 UTC, hoyajigi commented
@achimnol Done!

2024-01-08 05:14 UTC, studioego commented
I found the issue on Raspberry Pi5 with Debian OS.
![image](https://github.com/lablup/backend.ai/assets/20002/b7121bbf-16a0-44b4-884d-2f93f12fa177)

I checked the fix codes.

However, If $HOME/.local/bin is not in $PATH, I've checked that the error is as follows
(not found pants on PATH)
![image](https://github.com/lablup/backend.ai/assets/20002/5e5bdb35-996b-4931-ba86-72616981d144)

2024-01-08 05:17 UTC, studioego commented
Hmm. I found the PATH on the $HOME/.profile file.

after run the  
```shell
source ~/.profile
```
then , can run pants.

I think that LGTM

2024-01-08 05:51 UTC, studioego commented
LGTM!
It works good on Raspberry pi 5.

<img width="854" alt="image" src="https://github.com/lablup/backend.ai/assets/20002/3f8f1c8b-d12f-4b38-ab02-006142563fd0">

2024-01-08 05:51 UTC, studioego approved these changes
It works on Raspberry pi5 
<img width="854" alt="image" src="https://github.com/lablup/backend.ai/assets/20002/7a5b18e4-473e-4464-b82a-aaf7db03a13d">

2024-01-09 01:20 UTC, achimnol approved these changes

2024-01-09 01:25 UTC, merged