docs: add helper message for the allowed_session_types
lablup/backend.ai pull request #1885
Opened 2024-02-05 02:19 UTC by SangwonYoon

This PR resolves #1293 by adding helper message for the `allowed_session_types` in create and modify commands of scaling group.
The commands work well even without `allowed_session_types`, but since `allowed_session_types` is set to the default values of `interactive` and `batch`, it may not operate as intended by the user. 
Therefore, a helper message has been added.

2024-02-05 08:21 UTC, achimnol requested changes

2024-02-05 08:21 UTC, achimnol commented on src/ai/backend/client/cli/admin/scaling_group.py
> +        For 'allowed_session_types', if the key does not exist, the values 'interactive' and 'batch' are set.
Let's prefer the active voice.
```suggestion
        If the 'allowed_session_types' key is not specified, the policy defaults to accept both 'interactive' and 'batch'.
```

2024-02-05 08:21 UTC, achimnol commented on src/ai/backend/client/cli/admin/scaling_group.py
> +        For 'allowed_session_types', if the key does not exist, the values 'interactive' and 'batch' are set.
Same here.
```suggestion
        If the 'allowed_session_types' key is not specified, the policy defaults to accept both 'interactive' and 'batch'.
```

2024-02-16 02:37 UTC, fregataa approved these changes

2024-02-19 02:31 UTC, merged