fix: update netapp storage backend
lablup/backend.ai pull request #1983
Opened 2024-03-31 08:38 UTC by fregataa

resolves https://github.com/lablup/giftbox/issues/643

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-03-31 15:32 UTC, adrysn requested changes

2024-03-31 15:32 UTC, adrysn commented on configs/storage-proxy/sample.toml
> +netapp_group_id = 1100  # Owner group id. Must be created on Netapp mgmt server.
I think using the user and group IDs of the Storage Proxy should suffice. If the NetApp user and Storage Proxy user have different IDs, the Storage Proxy anyway cannot write files to the directory generated by Qtree, unless it is running with `root`.
https://github.com/lablup/backend.ai/blob/66c9e6c67d26958efa21b7c7ea8f7548cba445e0/configs/storage-proxy/sample.toml#L40-L41

2024-03-31 15:32 UTC, adrysn commented on src/ai/backend/storage/netapp/__init__.py
> +        self.netapp_client.check_job_result(result, ["5308507"])  # pass if "already on"
Add one more level of indent?

2024-04-01 07:25 UTC, fregataa commented
Converted this PR to a draft because DELETE folder API might need to be updated

2024-04-01 16:14 UTC, adrysn approved these changes

2024-04-04 05:47 UTC, merged