fix: Delete vfolders in own DB context when purge user
lablup/backend.ai pull request #2001
Opened 2024-04-06 04:41 UTC by fregataa

`PurgeUser.mutate()` deletes user related DB records, such as key pairs and vfolders.
But when a vfolder is being deleted through `PurgeUser.delete_vfolder()`,  the method opens own DB connection and deletes real data in storage.
Let's run `delete_vfolder()` in own context.

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation

2024-04-08 05:38 UTC, kyujin-cho requested changes
What would be the benefit of splitting VFolder removal procedure in a separate transaction? Please tell me more about it.

2024-04-08 06:23 UTC, fregataa commented
> What would be the benefit of splitting VFolder removal procedure in a separate transaction? Please tell me more about it.

When we purge user that has shared vfolders, an error below occurs.
```
asyncpg.exceptions._base.InternalClientError: cannot switch to state 11; another operation (2) is in progress
Collapse
```
It means we should not share a DB connection and should not open a new DB connection in a DB connection context. And this hotfix prevents the error.

2024-04-08 06:36 UTC, fregataa commented
> What would be the benefit of splitting VFolder removal procedure in a separate transaction? Please tell me more about it.

I thought this hotfix will prevent an issue about duplicate DB connection, but I'm wrong. So I changed this PR into a draft.

2024-07-11 08:46 UTC, fregataa commented
#2404 resolved this issue

2024-07-11 08:46 UTC, closed without merging