fix: Wrong usage of dataloader in GQL group resolver
lablup/backend.ai pull request #2056
Opened 2024-04-23 12:59 UTC by fregataa

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] API server-client counterparts (e.g., manager API -> client SDK)

2024-04-24 05:06 UTC, agatha197 approved these changes
LGTM

2024-04-26 02:59 UTC, jopemachine commented on src/ai/backend/manager/models/gql.py
> +                group for group in await loader.load(client_user_id) if group.type in type
On `groups` table definition, `type` column is non-nullable. May I ask why `null` check on `group.type` is necessary here?

2024-04-26 03:02 UTC, jopemachine commented
LGTM, but we also need to edit `resolve_groups`.
https://github.com/lablup/backend.ai/blob/056510689bdec33303dd85d1d0323f5777d5bfdf/src/ai/backend/manager/models/gql.py#L1005

2024-04-29 04:46 UTC, kyujin-cho requested changes

2024-04-29 04:46 UTC, kyujin-cho commented on src/ai/backend/manager/models/group.py
> +        type: list[ProjectType] | None = None,
Is there a specific reason you decided to expose every types of project by default here? When forming the model store sprint (which is directly related to this `type` parameter) we decided to reveal such projects only if the type was explicitly specified by requester.

2024-04-29 08:32 UTC, fregataa commented on src/ai/backend/manager/models/group.py
> +        type: list[ProjectType] | None = None,
I forgot to add this. it is restored now

2024-04-29 14:56 UTC, merged