feat: Support GitHub container registry
lablup/backend.ai pull request #2341
Opened 2024-06-26 07:38 UTC by jopemachine

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-06-26 07:38 UTC, jopemachine commented
* **#2341** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2341?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jopemachine and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-01 05:42 UTC, kyujin-cho requested changes

2024-08-01 05:42 UTC, kyujin-cho commented on src/ai/backend/manager/container_registry/__init__.py
> +        from .github import GitHubRegistry_v2
Given that we don't have any GitHub Registry support prior to this PR I don't think it is appropriate to call this class as `v2`.

2024-10-01 02:45 UTC, jopemachine commented
Closed as PR 1917 stack was merged.

2024-10-01 02:45 UTC, closed without merging