chore: Add SCIE binary build configs for the plugin subsystem
lablup/backend.ai pull request #2422
Opened 2024-07-11 02:51 UTC by jopemachine

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-07-11 02:52 UTC, jopemachine commented
* **#2422** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2422?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jopemachine and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-13 14:59 UTC, achimnol requested changes

2024-07-13 14:59 UTC, achimnol commented on src/ai/backend/plugin/BUILD
> +        "//src/ai/backend/accelerator/**",
During the build step, we don't ship the plugin subsystem with the accelerator plugins included. The accelerators should be loaded dynamically at runtime, not in the build-time.

2024-07-13 14:59 UTC, achimnol commented on src/ai/backend/plugin/BUILD
> +        "//src/ai/backend/accelerator/mock:buildscript",
Same here.

2024-07-17 07:52 UTC, achimnol approved these changes

2024-07-17 08:00 UTC, merged