feat: Add associate and disassociate mutations for multiple scaling groups with domains, key pairs, and user groups.
lablup/backend.ai pull request #2473
Opened 2024-07-15 09:26 UTC by agatha197

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-07-15 09:27 UTC, agatha197 commented
* **#2473** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2473?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-16 08:08 UTC, fregataa requested changes

2024-08-16 08:08 UTC, fregataa commented on src/ai/backend/manager/models/gql.py
> +        description="Added in 24.03.7"
Please update the version notation.
It should be `24.03.9` now

2024-08-16 08:08 UTC, fregataa commented on src/ai/backend/manager/models/scaling_group.py
> +    """Added in 24.03.7."""
Same here and all other mutation

2024-08-16 13:32 UTC, fregataa approved these changes

2024-08-16 13:36 UTC, merged