docs: Add `rpc-auth-manager-keypair`, which is a required setting
lablup/backend.ai pull request #2664
Opened 2024-08-07 03:00 UTC by Yaminyam

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-08-08 13:26 UTC, achimnol requested changes
Mostly LGTM except `install-agent.rst`.

2024-08-08 13:26 UTC, achimnol commented on docs/install/install-from-package/install-agent.rst
Assuming a multi-node setup, I think this shouldn't become 127.0.0.1.

2024-08-08 13:34 UTC, Yaminyam commented on docs/install/install-from-package/install-agent.rst
That was one of the things I struggled with the most, what value to put in there.
I decided to go with the values recommended in this file.
https://github.com/lablup/backend.ai/blob/9965d566537a8fb74b1b94dac855f12ad8333e05/configs/agent/sample.toml#L141
Please let me know if you think there are better values!

2024-09-04 14:24 UTC, kyujin-cho commented on docs/install/install-from-package/install-agent.rst
Strategy for setting bound and announced IPs are too complicated to mention in a single paragraph of explanation so I think it is better to split out whole section as a new documentation page.

2024-09-11 04:13 UTC, Yaminyam commented on docs/install/install-from-package/install-agent.rst
If so, I think it would be better to write a single-node based description for the current example and a separate multi-node based description.

2024-11-28 11:12 UTC, merged