ci: Allow adding required GQL field argument to schema
lablup/backend.ai pull request #2712
Opened 2024-08-13 14:31 UTC by fregataa

Allow adding required GQL field argument by relaxing `BREAKING` criticality level to `DANGEROUS`.
It has been prohibited to add a required field argument to existing types.
```gql
type Queries {
  vfolders(
    """Added in 24.09.0. This is a required argument and now it is allowed to add such field arguments."""
    project_id: UUID!
  }
}
```

**Checklist:** (if applicable)

- [x] Milestone metadata specifying the target backport version

2024-08-13 14:32 UTC, fregataa commented
* **#2712** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2712?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fregataa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-14 00:52 UTC, yomybaby requested changes

2024-08-14 00:52 UTC, yomybaby commented on gql-inspector-checker.js
> +        change.criticality.level = "WARNING";
Please refer to [the criticality level](https://github.com/kamilkisiela/graphql-inspector/blob/master/packages/core/src/diff/changes/change.ts#L1-L5). It's better to change to "DANGEROUS".

2024-08-14 00:55 UTC, yomybaby reviewed
After this PR is merged, please create a PR with the same changes to update the rule at https://github.com/lablup/graphql-inspactor-custom-rule

2024-08-14 01:27 UTC, Yaminyam commented
It would be great if you could provide an example in the text of how it will be used in the future!

2024-08-14 04:32 UTC, merged