ci: Verify that the current model schema and the migration file match
lablup/backend.ai pull request #2716
Opened 2024-08-14 11:25 UTC by Yaminyam

Validate that the alembic revision file matches the current model schema by checking that no changes were made when it was created.
The require:db-migration changes the trigger condition of check-alembic-migration because it is a label that we attach if there is a change in the actual revision file.

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version

2024-08-15 14:15 UTC, achimnol commented on .github/workflows/ci.yml
> +      run: python scripts/check-alembic-revision.py ${{ steps.create-revision.outputs.REVISION_FILE }}
Shouldn't we check the exit code to distinguish success and failure?

2024-08-15 14:16 UTC, achimnol commented on .github/workflows/ci.yml
> +    - name: Create a new revision
How about renaming this step to "Try creating alembic migration" to clearly indicate that this is not an actual revision but for a check, and make it clear that the revision is about alembic migrations (not a general term)?

2025-01-20 05:27 UTC, achimnol requested changes

2025-01-20 05:27 UTC, achimnol commented on scripts/check-alembic-revision.py
> +                        downgrade_has_pass = True
We should check if the only valid statement is `pass`, not just inclusion.

For instance,
```python
def upgrade():
    if something:
        pass
    else:
        some_operation()
```
could also satisfy this logic.

2025-02-07 02:08 UTC, HyeockJinKim approved these changes
lgtm

2025-02-07 07:55 UTC, achimnol commented
This is not what I meant....
I'd like to exclude the possibility of false-positive when there is a `pass` statement with a long body of `downgrade()` or `upgrade()` functions auto-generated.
My intention was to check if `downgrade()` and `upgrade()` functions are ***actually empty***, not just they contain `pass` _somewhere inside_.

2025-02-20 15:03 UTC, achimnol approved these changes

2025-02-20 15:06 UTC, merged