feat: Add GQL schema to query total resource slots
lablup/backend.ai pull request #2849
Opened 2024-09-19 10:56 UTC by fregataa

The new GQL schema allows total resource slots of compute sessions that belong to certain scopes or compute sessions specified by conditions.
`project_id`, `domain_name`, `resource_group_name` and `filter` arguments are available and the resolver raises error if none of the arguments is specified.

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] API server-client counterparts (e.g., manager API -> client SDK)

2025-03-18 08:28 UTC, agatha197 commented on src/ai/backend/manager/models/gql_models/session.py
> +            occupied_slots=occupied,
occupying_slots, occupied_slots are both return occupied. what's the purpose?

2025-03-18 09:00 UTC, agatha197 requested changes
there're typo errors

2025-03-18 09:00 UTC, agatha197 commented on docs/manager/graphql-reference/schema.graphql
> +    `filter` argument is a string that is parsed into query conditions. It works in the same way as the `fileter` argument in the `compute_session` query schema, meaning the values are parsed into an
```suggestion
    `filter` argument is a string that is parsed into query conditions. It works in the same way as the `filter` argument in the `compute_session` query schema, meaning the values are parsed into an identical SQL query expression.
```

2025-03-18 09:00 UTC, agatha197 commented on src/ai/backend/manager/models/gql.py
> +                "It works in the same way as the `fileter` argument in the `compute_session` query schema, "
```suggestion
                "It works in the same way as the `filter` argument in the `compute_session` query schema, "
```

2025-03-20 08:24 UTC, agatha197 requested changes

2025-03-20 08:24 UTC, agatha197 commented on src/ai/backend/manager/models/gql_models/session.py
> +    "images": (ArrayFieldItem("images"), None),
```suggestion
    "image": (ArrayFieldItem("images"), None),
```

2025-03-20 08:36 UTC, agatha197 approved these changes
LGTM

2025-03-24 02:24 UTC, yomybaby approved these changes
LGTM

2025-03-25 05:57 UTC, HyeockJinKim commented on src/ai/backend/manager/models/session.py
> +    return _and_user_id
`and_...` functions don't look very natural.

2025-03-25 12:15 UTC, merged