feature: Add info fields to GQL image schema
lablup/backend.ai pull request #2939
Opened 2024-10-22 09:14 UTC by fregataa

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-10-22 09:14 UTC, fregataa commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2939?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2939** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2939?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2938** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/2938?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fregataa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-31 05:31 UTC, agatha197 approved these changes
LGTM

2024-10-31 06:45 UTC, agatha197 requested changes
If tags include `customized_` in the key, could you change the tag value to the value of the label whose key is `ai.backend.customized-image.name` ??

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/7e8bcc2e-af3c-4014-ace2-c4586d979ced.png)

Currently, it looks like this. Users will identify images based on the content they input in the session name when committing the session. The images are stored with hash values. Therefore, it is difficult to differentiate which image was committed with what name using the current tag.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/2HueYSdFvL8pOB5mgrUQ/cf3d3f47-bb82-4371-911d-20ea7a328992.png)

2024-10-31 08:04 UTC, agatha197 approved these changes

2024-10-31 08:04 UTC, agatha197 approved these changes

2024-10-31 08:04 UTC, agatha197 approved these changes

2024-11-05 02:47 UTC, agatha197 requested changes
Please change target version and codes to 24.12.0

2024-11-05 06:38 UTC, agatha197 requested changes

2024-11-05 06:38 UTC, agatha197 commented on src/ai/backend/manager/models/gql_models/image.py
> +    base_image_name = graphene.String(description="Added in 24.12.0..")
```suggestion
    base_image_name = graphene.String(description="Added in 24.12.0.")
```
And it's the same below.

2024-11-05 06:55 UTC, agatha197 approved these changes
LGTM

2024-11-05 06:59 UTC, merged