feat: Implement `AssociationContainerRegistriesGroupsRow`
lablup/backend.ai pull request #3065
Opened 2024-11-11 02:03 UTC by jopemachine

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-11-11 02:03 UTC, jopemachine commented
* **#3036** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3036?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3035** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3035?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3065** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3065?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jopemachine and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-11 05:57 UTC, jopemachine commented on src/ai/backend/manager/models/alembic/versions/8f85e9d0bd4e_add_association_containerregistries_.py
> +def upgrade() -> None:
Previously, there was no per-project image lookup functionality, so a data migration logic was unnecessary here.

2024-11-13 04:42 UTC, fregataa requested changes

2024-11-13 04:42 UTC, fregataa commented on src/ai/backend/manager/models/association_container_registries_groups.py
> +        sa.ForeignKey("container_registries.id", onupdate="CASCADE", ondelete="CASCADE"),
We recommend not to use foreign key constraint anymore in backend.ai.
Please check [this code](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/models/vfolder.py#L455-L459) how to load related rows without a foreign key constraint.

2024-11-13 04:42 UTC, fregataa commented on src/ai/backend/manager/models/association_container_registries_groups.py
> +        sa.ForeignKey("groups.id", onupdate="CASCADE", ondelete="CASCADE"),
same here

2024-11-14 06:25 UTC, fregataa requested changes
How about adding the new table definition in an existing file such as `models/container_registries.py` or `models/groups.py`?

2024-11-14 06:25 UTC, fregataa commented on src/ai/backend/manager/models/association_container_registries_groups.py
> +
Please add an unique constraint on `registry_id` and `group_id`

2024-11-18 01:46 UTC, jopemachine commented
> How about adding the new table definition in an existing file such as `models/container_registries.py` or `models/groups.py`? This is just a suggestion, you don't need to reflect it right away.

Personally, I think it’s better to place them in separate files.
Having a single file for each table, rather than defining multiple tables in one file, seems more intuitive and makes it easier to refer back to them later.

2025-01-06 05:58 UTC, fregataa reviewed
I left a comment. And more questions are:
- Is the target milestone 24.12 ?
- Let's discuss about where to locate the definition of association tables

2025-01-06 05:58 UTC, fregataa commented on src/ai/backend/manager/models/alembic/versions/8f85e9d0bd4e_add_association_containerregistries_.py
> +    op.drop_table("association_container_registries_groups")
isn't dropping unique constraint required here?
I'm curious cause I had an issue when I tried to delete a table without dropping some constraints.

2025-01-06 06:21 UTC, jopemachine commented on src/ai/backend/manager/models/alembic/versions/8f85e9d0bd4e_add_association_containerregistries_.py
> +    op.drop_table("association_container_registries_groups")
The `downgrade` function seems to be working as expected without adding a constraint drop.
It appears that when the table is dropped, the constraints associated with that table are also dropped.

```
❯ ./py -m alembic downgrade -1
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade 8f85e9d0bd4e -> 0bb88d5a46bf, Add association table with `ContainerRegistries`, and `Groups` table.

❯ ./py -m alembic upgrade +1
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 0bb88d5a46bf -> 8f85e9d0bd4e, Add association table with `ContainerRegistries`, and `Groups` table.
```

2025-01-06 06:27 UTC, jopemachine commented
> * Is the target milestone 24.12 ?

The originally intended milestone was 24.12, but since its priority has been pushed back, it seems it should be reset to 25.Q1.

> * Let's discuss about where to locate the definition of association tables

I think it would be better to place the Association table in a separate file.
If that is not the case, we need to decide and standardize whether the `AssociationAWithB` table should be located in `A.py` or `B.py`. 

I believe placing it in a separate file is more explicit rather than this.

2025-02-06 02:40 UTC, HyeockJinKim commented
The CI has failed. Could you please check it? @jopemachine

2025-02-06 03:52 UTC, jopemachine commented
> The CI has failed. Could you please check it? @jopemachine

@HyeockJinKim This PR doesn't touch graphql schema, but the CI error message complain about it.
Looking at the error message, I have no idea about why, but it’s checking out PR #3424.
(Since PR #3424 includes an API breaking change, the CI failure is expected behavior.)

```
Run kamilkisiela/graphql-inspector@release-1717403590269
GraphQL Inspector started
Ref: 4b1b[7](https://github.com/lablup/backend.ai/actions/runs/13151640560/job/36700069179?pr=3065#step:3:8)5cbe0e7072f31644cfd99cb9ff49f6647e5
Commit SHA: 3ecb00c99ba9[8](https://github.com/lablup/backend.ai/actions/runs/13151640560/job/36700069179?pr=3065#step:3:9)16310df576935d324efe7222a5c
Creating a check named "GraphQL Inspector"
Check ID: 36700073763
EXPERIMENTAL - Using Pull Request refs/pull/3424/merge
EXPERIMENTAL - Using topic/[11](https://github.com/lablup/backend.ai/actions/runs/13151640560/job/36700069179?pr=3065#step:3:12)-11-feat_implement_associatecontainerregistrywithgroup_disassociatecontainerregistrywithgroup_ as base schema ref
Query topic/11-11-feat_implement_associatecontainerregistrywithgroup_disassociatecontainerregistrywithgroup_:docs/manager/graphql-reference/schema.graphql from lablup/backend.ai
Query refs/pull/3424/merge:docs/manager/graphql-reference/schema.graphql from lablup/backend.ai
Got both sources
Built both schemas
Start comparing schemas
Changes: 28
Conclusion: failure
Updating check: 36700073763
annotations to be sent: 28
annotations sent (28)
Error: Something is wrong with your schema
```

2025-02-13 07:41 UTC, merged