feat: Implement `AssociateContainerRegistryWithGroup`, `DisassociateContainerRegistryWithGroup`
lablup/backend.ai pull request #3067
Opened 2024-11-11 05:41 UTC by jopemachine

**Checklist:** (if applicable)

- [ ] Milestone metadata specifying the target backport version
- [ ] Mention to the original issue
- [ ] Installer updates including:
  - Fixtures for db schema changes
  - New mandatory config options
- [ ] Update of end-to-end CLI integration tests in `ai.backend.test`
- [ ] API server-client counterparts (e.g., manager API -> client SDK)
- [ ] Test case(s) to:
  - Demonstrate the difference of before/after
  - Demonstrate the flow of abstract/conceptual models with a concrete implementation
- [ ] Documentation
  - Contents in the `docs` directory
  - docstrings in public interfaces and type annotations

2024-11-11 05:42 UTC, jopemachine commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3067?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3036** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3036?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3035** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3035?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#3067** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3067?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#3065** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai/3065?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jopemachine and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-12 05:18 UTC, jopemachine commented on src/ai/backend/manager/api/container_registry.py
> +    app["api_versions"] = (1, 2, 3, 4, 5)
TODO: The current value is just a temporary placeholder, and I need to check what value should be set for `api_versions`.

2024-11-14 05:59 UTC, jopemachine commented on src/ai/backend/manager/api/container_registry.py
> +    app["api_versions"] = (1, 2, 3, 4, 5)
This value does not appear to be used in any validation logic in the current codebase. 
Let’s address this in a separate issue.

2024-11-27 08:41 UTC, HyeockJinKim approved these changes

2024-12-06 04:28 UTC, jopemachine commented on tests/manager/models/gql_models/test_container_registries.py
> +    extra_fixtures, client: Client, test_case, database_fixture, create_app_and_client
TODO: fix this

2025-01-06 06:15 UTC, fregataa requested changes

2025-01-06 06:15 UTC, fregataa commented on src/ai/backend/manager/api/container_registry.py
> +)
How about using [pydantic_params_api_handler()](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/utils.py#L269) ?

reference:
https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/service.py#L328-L395
https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/service.py#L532

2025-01-06 06:15 UTC, fregataa commented on src/ai/backend/manager/api/container_registry.py
> +)
same here

2025-01-06 06:15 UTC, fregataa commented on src/ai/backend/manager/api/container_registry.py
> +    return web.json_response({})
How about returning empty http response with 204 status, not json response?

2025-01-06 06:15 UTC, fregataa commented on src/ai/backend/manager/api/container_registry.py
> +    return web.json_response({})
same here

2025-01-08 08:10 UTC, HyeockJinKim commented on src/ai/backend/manager/models/gql.py
> +        description="Added in 25.01.0."
25.1.0

2025-02-10 09:40 UTC, jopemachine commented
All the contents of this PR will be overwritten by the next PR, so it is useless.
Therefore, I will remove this PR from the PR stack and close it.

2025-02-10 10:25 UTC, closed without merging