feat: allow user to force-terminate own sessions
lablup/backend.ai pull request #525
Opened 2022-07-08 05:53 UTC by Sujin-Kim1

Allow general users to force termination of their own sessions. (NOT OTHERS')
Related PR: https://github.com/lablup/backend.ai-webui/pull/1358

2022-07-13 05:02 UTC, adrysn requested changes

2022-07-13 05:02 UTC, adrysn commented on src/ai/backend/manager/api/session.py
> +    if requester_access_key != owner_access_key and request['user']['role'] not in (UserRole.ADMIN, UserRole.SUPERADMIN):
Where is the parameter, forced?

2022-07-14 02:31 UTC, adrysn approved these changes
LGTM.

2022-07-14 02:31 UTC, adrysn commented on src/ai/backend/manager/api/session.py
> +    if requester_access_key != owner_access_key and request['user']['role'] not in (UserRole.ADMIN, UserRole.SUPERADMIN):
Oh, sorry. On a second look, this logic is correct.

2022-07-18 09:20 UTC, achimnol approved these changes

2022-07-18 09:20 UTC, merged