refactor: separate duplicate decorators from start and run
lablup/backend.ai pull request #537
Opened 2022-07-11 08:28 UTC by Yaminyam

Due to the reduced readability due to overlapping decorators, the commonly needed decorators have been integrated into one decorator.

2022-08-01 02:06 UTC, achimnol requested changes
How about rename `args` module to `_args` to distinguish it (a utility-containing module) from other command-containing modules?

2022-08-01 02:06 UTC, achimnol commented on changes/537.misc.md
> +Rename `run.py` to `execute.py` and separate it into session submodule
The changelog should be in one single sentence written in a single line. If there are multiple notable changes, please summarize the intention and the collective goal.

2022-09-12 11:53 UTC, fregataa reviewed
looks good!
I leave comments

2022-09-12 11:53 UTC, fregataa commented on src/ai/backend/client/cli/session/args.py
> +def click_start_option():
How about adding type hint of return value?
And I suggest to declare the options in one list as a constant.
like the below.
```
START_OPTION = [
    click.option(),
    click.option(),
    ...
]
```

2023-03-02 01:33 UTC, achimnol requested changes
Let's leave comments after the command handler functions' args to indicate that which args are from which decorator.

e.g.,

```python
    @some_other_option()
    @click_start_option()
    def create(
        # base args
        image: str,                             # some_other_option
        name: str | None,                       # click_start_option
        owner: str | None,                      # some_other_option
        type: Literal["batch", "interactive"],  # click_start_option
        starts_at: str | None,                  # click_start_option
        startup_command: str | None,            # click_start_option
        enqueue_only: bool,                     # click_start_option
        max_wait: int,                          # click_start_option
        no_reuse: bool,                         # click_start_option
...
```

2023-03-26 03:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lablup/backend.ai?pullRequest=537) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/lablup/backend.ai?pullRequest=537) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kyujin-cho<br/>:x: Yaminyam<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lablup/backend.ai?pullRequest=537) it.</sub>

2023-08-23 09:41 UTC, achimnol approved these changes
It's too late, but I think the refactoring of client SDK's session CLI module/subpkg is a nice thing to have. I see no apparent regression in this PR, so let's first merge it.

2023-08-23 09:44 UTC, merged