feat: Add pause, unpause type to kernel lifecycle
lablup/backend.ai pull request #672
Opened 2022-08-22 07:01 UTC by Yaminyam

https://github.com/lablup/backend.ai/pull/629 isolated from pr
Added pause and unpause to kernel lifecycle types.

2022-09-02 06:35 UTC, fregataa reviewed
good!
how about let pause_kernel and unpause_kernel methods in kubernetes.agent module raise `NotImplementedError`?

2022-09-19 14:56 UTC, kyujin-cho approved these changes

2022-09-19 14:56 UTC, kyujin-cho commented on src/ai/backend/agent/agent.py
> +        pass
Please implement these methods on Kubernetes backend also. If you don't have any knowledge about Kubernetes, it's okay to let implementations as blank and create separate issue stating we have to implement it later.

2022-09-19 14:57 UTC, kyujin-cho requested changes

2022-09-19 14:57 UTC, kyujin-cho commented on src/ai/backend/agent/agent.py
> +        pass
Please implement these methods on Kubernetes backend also. If you don't have any knowledge about Kubernetes, it's okay to let implementations as blank and create separate issue stating we have to implement it later.

2022-10-18 18:41 UTC, s4shantanu approved these changes

2023-01-20 11:43 UTC, achimnol requested changes

2023-01-20 11:43 UTC, achimnol commented on src/ai/backend/agent/docker/agent.py
> +                                    break
I remember that Python's match syntax does not 'fall-through' to the subsequent case blocks. Please remove these unnecessary `break` statements, unless you are intending to exit the entire subscription loop!

2023-01-20 16:41 UTC, s4shantanu reviewed
Looks good to me!!

2023-03-26 03:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lablup/backend.ai?pullRequest=672) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/lablup/backend.ai?pullRequest=672) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kyujin-cho<br/>:x: Yaminyam<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lablup/backend.ai?pullRequest=672) it.</sub>

2023-08-01 08:57 UTC, achimnol commented
As #629 is superseded by #1373, I'm closing this as well.
Currently it's not practical to forcibly pause a container (i.e., excluding the container processes from the Linux scheduler) as this will make it unresponsive at all while the container still occupies the agent resources.

2023-08-01 08:57 UTC, closed without merging