feat: Do not return AgentSummary if hide-agents is true
lablup/backend.ai pull request #699
Opened 2022-08-31 17:27 UTC by fregataa

do not return AgentSummary and AgentSummaryList gql objects if `hide-agents` is true.

Follow-up of #645.
Resolves #640.

2022-09-01 02:34 UTC, adrysn commented
I'm not sure, but wouldn't it be better to raise 404 NotFound error instead of returning the empty results to hide the queries themselves?

2022-09-02 06:14 UTC, fregataa commented
> I'm not sure, but wouldn't it be better to raise 404 NotFound error instead of returning the empty results to hide the queries themselves?

that would be nice cause handling query at model interface by reading config seems inappropriate.

2022-09-04 03:17 UTC, adrysn approved these changes
Tested and works for me.

2022-09-12 11:39 UTC, kyujin-cho requested changes

2022-09-12 11:39 UTC, kyujin-cho commented on src/ai/backend/manager/models/gql.py
> +        if ctx.local_config["manager"]["hide-agents"]:
Please add corresponding config definition on manager's local config scheme, `manager_local_config_iv`.

2022-09-12 11:40 UTC, kyujin-cho approved these changes

2022-09-13 00:09 UTC, merged