feat: Add class KernelLifecycleEventReason to manage KernelEvent.reason
lablup/backend.ai pull request #700
Opened 2022-09-01 09:03 UTC by qkoo0833

1. Add class `KernelLifecycleEventReason` in common/events.py to manage `kernelEvent.reason`

2. change string-literal to constant variable using KernelLifecycleEventReason

#678

2022-09-01 10:18 UTC, rapsealk requested changes

2022-09-01 10:18 UTC, rapsealk commented on changes/700.feature.md
> +feat: Add class KernelLifecycleEventReason to manage KernelEvent.reason
This is not a valid style for changelogs. Please refer [changes/README](https://github.com/lablup/backend.ai/blob/main/changes/README.md).

2022-09-12 09:13 UTC, kyujin-cho requested changes
Thank you for your contribution! Here are some points which can be enhanced.

2022-09-12 09:13 UTC, kyujin-cho commented on src/ai/backend/common/events.py
> +class KernelLifecycleEventReason:
The recommended way to group multiple values as a single category is to use `enum.Enum` (ref: https://github.com/lablup/backend.ai/blob/bede3c289c0a2b3620d07e061d986f52898654d9/src/ai/backend/common/types.py#L232). Please update this class to inherit `enum.Enum`. Don't forget to update type definition on code which accepts `KernelLifecycleEventReason` also!

2022-09-14 07:54 UTC, closed without merging