fix: Fix wrong type matching in scaling group query method
lablup/backend.ai pull request #738
Opened 2022-09-23 14:46 UTC by fregataa

2022-09-25 00:47 UTC, adrysn approved these changes
LGTM. Tested and it works.

2022-09-27 12:47 UTC, kyujin-cho requested changes

2022-09-27 12:47 UTC, kyujin-cho commented on src/ai/backend/manager/models/scaling_group.py
> +            group_ids = [*grps]
Is there a specific reason unpacking and repacking `list` instead of using as is?

2022-09-28 05:58 UTC, kyujin-cho approved these changes

2022-09-28 06:00 UTC, merged