docs: translated to korean manager/user-api/vfolders.po
lablup/backend.ai pull request #828
Opened 2022-10-22 07:20 UTC by yeslee-v

@lizable, Added korean translation for installation for #816 

I translated [vfloders page](https://github.com/lablup/backend.ai/blob/main/docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po).

2022-10-22 09:27 UTC, Yaminyam approved these changes

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "여러분은 새로운 세션을 생성할 때 가상 폴더를 마운트할 수 있으며, "
Where did the expression "여러분은" come from?

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "또한, 여러분은 가상 폴더를 다른 사용자와 공유할 수 있으며, "
Same here as above.

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "(선택 사항) 매개 변수가 ``True`` 인 경우, 현재 사용자가 속하지 않는 모든 가상 폴더를 반환합니다. 슈퍼 관리자만이 해당 매개변수를 사용할 수 있습니다 (기본값: ``False``)."
It seems better to use the expression "최고관리자" or "superadmin" as it is rather than putting superadmin in the original notation.

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "성공"
It seems good to keep the punctuation marks in the original text.

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "없음"
Same here as above.

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +"invitation(s). Only group virtual folders are allowed to be shared directly. "
Why is there a space at the end of the sentence?

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgid "NOTE: This API is only available for group virtual folders. "
There is also a space at the end here.

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "공유할 사용자 이메일 목록"
There are no punctuation marks in the original text.

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "허가나 이메일이 주어지지 않았습니다."
It seems better to translate it as "권한" rather than "허가".

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "새 가상 폴더의 이름"
There are no punctuation marks in the original text.

2022-10-22 09:27 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
>  msgid "The targe host volume of the new virtual folder."
There are no punctuation marks in the original text.

2022-10-22 09:28 UTC, Yaminyam reviewed
You've done a lot of work!

2022-10-22 16:12 UTC, Yaminyam commented
If the original text is not sentence-like, I decided again that it would be better to delete the whole point in the original text and also in the translation!

2022-10-24 09:50 UTC, yeslee-v commented
Thanks to feedback, @Yaminyam.

update translation, please check again 😃

2022-10-24 10:57 UTC, Yaminyam requested changes

2022-10-24 10:57 UTC, Yaminyam commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "새 가상 폴더의 이름."
Since the original text is not a sentence, it is correct to remove the dot from both the original text and the translation.

2022-10-24 11:19 UTC, yeslee-v commented
update translation, please check again 🥲 @Yaminyam.

2022-10-24 11:26 UTC, Yaminyam commented
Please delete the dot in the original English text that is not in the form of a sentence!

2022-10-24 12:37 UTC, yeslee-v commented
include your feedback!

2022-10-24 12:57 UTC, yeslee-v commented
When i check the changed page, but it doesn't updated!
please check this issue! @lizable

2022-10-24 16:24 UTC, Yaminyam approved these changes

2022-10-28 08:25 UTC, kyujin-cho requested changes
These are reviews to match the consistency of documents.

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "(선택 사항) 매개 변수가 ``True`` 인 경우, 현재 사용자가 속하지 않는 모든 가상 폴더를 반환합니다. 최고 관리자만이 해당 매개변수(기본값: ``False``)를 사용할 수 있습니다."
```suggestion
msgstr "(선택 사항) 매개 변수가 ``True`` 인 경우, 현재 사용자가 속하지 않는 폴더를 포함한 모든 가상 폴더를 반환합니다. 최고 관리자만이 해당 매개변수(기본값: ``False``)를 사용할 수 있습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "현재 API 키와 연결된 가상 폴더 생성합니다."
```suggestion
msgstr "현재 API 키와 연결된 가상 폴더를 생성합니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +"디렉토리 단위 쿼터를 지원하지 않는 다른 파일 시스템은 해당 매개 변수를 무시합니다."
```suggestion
"디렉토리 단위 쿼터를 지원하지 않는 다른 파일 시스템에서는 해당 매개 변수가 무시됩니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "커널은 성공적으로 생성되었습니다."
```suggestion
msgstr "커널이 성공적으로 생성되었습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "이름은 잘못되었거나 이미 존재하는 가상 폴더와 중복됩니다."
```suggestion
msgstr "잘못되었거나 이미 존재하는 가상 폴더와 중복되는 이름입니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "최신 API 호출을 위해 사용되는 고유한 폴더 ID"
```suggestion
msgstr "이후의 API 호출을 위해 사용되는 고유한 폴더 ID"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "정보는 성공적으로 반환되었습니다."
```suggestion
msgstr "정보가 성공적으로 반환되었습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "폴더는 성공적으로 삭제되었습니다."
```suggestion
msgstr "폴더가 성공적으로 삭제되었습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "가상 폴더(기본값: root) 내 경로"
```suggestion
msgstr "가상 폴더 내 경로 (기본값: root)"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "재귀 옵션을 True로 설정하지 않고 폴더를 삭제하려고 했습니다."
```suggestion
msgstr "recursive 옵션을 True로 설정하지 않고 폴더를 삭제하려고 했습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "가상 폴더 내 파일 이름 변경하기"
```suggestion
msgstr "가상 폴더 내 파일 이름을 변경하기"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "타겟 파일 또는 디렉토리의 상대 경로"
```suggestion
msgstr "대상 파일 또는 디렉토리의 상대 경로"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "요청한 사용자가 받은 보류중인 초대 목록을 반환합니다. 이 목록은 다른 사용자가 보낸 초대가 표시됩니다."
```suggestion
msgstr "요청한 사용자가 받은 보류중인 초대 목록을 반환합니다. 이 목록에는 다른 사용자가 보낸 초대가 표시됩니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +"사용자가 이미 초대되어 있다면 이 API는 새로운 초대를 생성하지 않거나 기존 초대 권한을 업데이트하지 않습니다."
```suggestion
"해당 사용자가 이미 초대되어 있다면 이 API는 새로운 초대를 생성하지 않거나 기존 초대 권한을 업데이트하지 않습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "초대를 수락하고 초대에 따른 가상 폴더의 권한을 받습니다."
```suggestion
msgstr "초대를 수락하고 초대에 따른 가상 폴더의 권한을 부여받습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "타겟 가상 폴더 이름이 이미 존재하는 가상 폴더 이름과 중복됩니다."
```suggestion
msgstr "대상 가상 폴더 이름이 이미 존재하는 가상 폴더 이름과 중복됩니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "초대 목록에 대한 상세 메시지"
```suggestion
msgstr "초대 철회에 대한 상세 메시지"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "공유된 가상 폴더 나가기"
```suggestion
msgstr "공유받은 가상 폴더 나가기"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "공유된 가상 폴더에서 나갑니다."
```suggestion
msgstr "공유받은 가상 폴더에서 나갑니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "노트: 이 API는 그룹 가상 폴더에만 사용할 수 있습니다."
```suggestion
msgstr "안내: 이 API는 그룹 가상 폴더에만 사용할 수 있습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "사용자 이메일 목록이 성공적으로 가상 폴더에 공유되었습니다."
```suggestion
msgstr "가상 폴더를 공유중인 사용자의 이메일 목록."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "사용자 이메일 목록이 성공적으로 가상 폴더 공유를 해제했습니다."
```suggestion
msgstr "가상 폴더 공유 해제를 완료한 사용자의 이메일 목록."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "만약 ``True`` 라면, 복제된 가상 폴더는 다시 복제할 수 있습니다."
```suggestion
msgstr "``True``일 경우, 복제된 가상 폴더를 다시 복제할 수 있습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "가상 폴더는 다른 세션에서 공유되고, 지속적으로 사용되고, 재사용되는 파일에 접근할 수 있습니다."
가상 폴더는 여러 다른 세션애서 공유되며, 지속적이고, 재사용 가능한 파일을 제공합니다.

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "현재 키쌍으로 생성된 가상 폴더의 목록을 반환합니다."
Keypair is commonly used as proper noun on technical documents, so it'll be better to let it as-is.

```suggestion
msgstr "현재 키페어로 생성된 가상 폴더의 목록을 반환합니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "새로운 가상 폴더를 만들 수 있는 현재 keypair의 호스트 이름 목록을 반환합니다."
```suggestion
msgstr "새로운 가상 폴더를 만들 수 있는 현재 키페어의 호스트 이름 목록을 반환합니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "사람이 읽을 수 있는 생성된 가상 폴더 이름"
```suggestion
msgstr "생성된 가상 폴더의 사람이 읽을 수 있는 이름"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "삭제된 가상 폴더를 마운트한 실행 중인 커널이 있다면, 해당 커널은 깨질 수 있습니다!"
```suggestion
msgstr "실행 중인 커널 중 삭제된 가상 폴더를 마운트한 커널이 있다면, 해당 커널은 오작동할 수 있습니다!"
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "현재 키쌍과 연결된 가상 폴더 내 파일 목록을 반환합니다."
```suggestion
msgstr "현재 키페어와 연결된 가상 폴더 내 파일 목록을 반환합니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "현재 keypair와 연결된 가상 폴더에 로컬 파일을 업로드합니다. "
```suggestion
msgstr "현재 키페어와 연결된 가상 폴더에 로컬 파일을 업로드합니다. "
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "저장-프록시에 대한 요청 URL. 클라이언트는 이 URL을 사용하여 파일을 업로드해야 합니다."
Storage-Proxy is a service name, so it should be treated as a proper noun.

```suggestion
msgstr "저장-프록시에 대한 요청 URL. 클라이언트는 이 URL을 사용하여 파일을 업로드해야 합니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "현재 keypair에서 연결된 가상 폴더에 새 디렉토리를 생성합니다. "
```suggestion
msgstr "현재 키페어에 연결된 가상 폴더에 새 디렉토리를 생성합니다. "
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "만약 ``True`` 일 때, 상위 디렉토리가 존재하지 않으면 생성됩니다."
```suggestion
msgstr "``True`` 일 경우, 지정한 상위 디렉토리가 존재하지 않으면 같이 생성합니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "vfolder 그룹 또는 요청한 사용자가 소유한 vfolder는 나갈 수 없습니다."
```suggestion
msgstr "그룹 vfolder 또는 요청한 사용자가 소유한 vfolder는 나갈 수 없습니다."
```

2022-10-28 08:25 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "권한이 없습니다."
```suggestion
msgstr "권한을 지정하지 않았습니다."
```

2022-10-30 11:44 UTC, yeslee-v commented
update docs, @kyujin-cho
and please add a label `hacktoberfest-accepted`😃

2022-10-31 05:36 UTC, kyujin-cho requested changes
Just a small typo!

2022-10-31 05:36 UTC, kyujin-cho commented on docs/locales/ko/LC_MESSAGES/manager/user-api/vfolders.po
> +msgstr "가상 폴더는 여러 다른 세션애서 공유되며, 지속적이고, 재사용 가능한 파일을 제공합니다."
Please fix typo here.
```suggestion
msgstr "가상 폴더는 여러 다른 세션에서 공유되며, 지속적이고, 재사용 가능한 파일을 제공합니다."
```

2022-10-31 06:33 UTC, yeslee-v commented
fix word and check again please, @kyujin-cho

2022-10-31 10:28 UTC, kyujin-cho approved these changes
LGTM!

2022-10-31 10:28 UTC, merged