feat: impl minimal vfolder trash bin
lablup/backend.ai pull request #835
Opened 2022-10-24 07:41 UTC by fregataa

related issue: #767 
This pr does not fully cover the related issue because this does not include auto-clearing trash bin

2022-11-04 07:52 UTC, kyujin-cho requested changes
We need retention period feature for trash bin. Manager creates a timer for a function which looks for vFolders staying more than designated period at the trash bin and purging them automatically.

2022-11-17 09:09 UTC, fregataa commented
TODO
1. Should we include the trash-bin in vfolder metrics?
2. Should users have personal/group-owned trash bin? Because host-unique trash bin makes it hard to determine whose *trash* it is

2022-12-30 07:29 UTC, achimnol requested changes
* Let's migrate the configuration option to the etcd, as a globally shared config.
* Could you describe what's the context of adding explicit `DoCheckStorageEvent` with logging of the number of vfolders in the trash bin?

2022-12-30 07:29 UTC, achimnol commented on changes/835.feature.md
> +impl minimal vfolder trash bin.
Please use a full sentence.
```suggestion
Implement a folder-level trash bin to allow recovery of accidentally deleted vfolders
```

2023-01-03 17:44 UTC, fregataa commented
> * Could you describe what's the context of adding explicit `DoCheckStorageEvent` with logging of the number of vfolders in the trash bin?

I added `DoCheckStorageEvent` to check trash bin regularly to empty it or log the status of it.

2023-10-04 03:25 UTC, kyujin-cho requested changes

2023-10-04 03:25 UTC, kyujin-cho commented on src/ai/backend/manager/defs.py
> +    LOCKID_STORAGE_TIMER = 197
Looks like this LockID is not used anymore.

2023-10-04 03:25 UTC, kyujin-cho commented on src/ai/backend/manager/models/vfolder.py
> +    # PURGE_COMPLETE = "purged-complete"  # vfolder is removed permanently
Please remove commented out, unused snippet from the file.

2023-10-04 03:25 UTC, kyujin-cho commented on src/ai/backend/manager/api/vfolder.py
> +            # if UPDATABLE access status is requested, only READY operation status is accepted.
Looks like this comment contradicts with actual implementation.

2023-10-04 05:55 UTC, merged