feature: host networking container
lablup/backend.ai pull request #838
Opened 2022-10-25 10:58 UTC by kyujin-cho

2022-10-28 02:52 UTC, achimnol reviewed
First batch of comments:
- If you replace the local input handler with `/tmp/bai-user-input.sock`, libbaihook should be also updated. Please link this PR from there.
- `use_host_network` should be configurable by individual agents, instead of by manager's local config, I think.

2022-10-28 07:34 UTC, kyujin-cho commented
Created corresponding PR on lablup/backend.ai-hook#4.

2022-11-08 08:42 UTC, achimnol requested changes
Please fix up relatively minor code-level issues.
The overall implementation looks good!

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/agent/server.py
> +    async def collect_port(self, port_no: int):
How about renaming this to `release_port()`?

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/kernel/base.py
> +                return intrinsic_host_ports_mapping_path.read_text()
This could be simplified using a lambda function. :wink:

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/agent/agent.py
>                  "protocol": ServicePortProtocols("tcp"),
It's a valid expression but `SeviceProtocols.TCP` would be more idiomatic, which does not include an additional enum lookup.
```suggestion
                "protocol": ServicePortProtocols.TCP,
```

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/agent/agent.py
>                  "protocol": ServicePortProtocols("http"),
Same here.
```suggestion
                "protocol": ServicePortProtocols.HTTP,
```

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/agent/agent.py
>                      "protocol": ServicePortProtocols("preopen"),
Same here.
```suggestion
                    "protocol": ServicePortProtocols.PREOPEN,
```

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/agent/agent.py
> +                        "protocol": ServicePortProtocols("internal"),
Same here.
```suggestion
                        "protocol": ServicePortProtocols.INTERNAL,
```

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/agent/docker/agent.py
> +                    fw.write(json.dumps(intrinsic_ports))
This could be simplified as:
`(self.config_dir / "intrinsic-ports.json").write_text(json.dumps(intrinsic_ports))`
and passed as a lambda function to `run_in_executor()`.

Or, to keep the verbose file opens:
```suggestion
                with open(self.config_dir / "intrinsic-ports.json", "w") as fw:
                    json.dump(intrinsic_ports, fw)
```

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/agent/docker/agent.py
> +                    intrinsic_ports["ttyd"] = host_ports[index + 2]
```suggestion
            for index, port_info in enumerate(service_ports[2:], start=2):
                port_name = port_info["name"]
                if port_name in ("sshd", "ttyd"):
                    intrinsic_ports[port_name] = host_ports[index]
```

2022-11-08 08:42 UTC, achimnol commented on src/ai/backend/manager/config.py
> +                    t.Key("use-host-network", default=False): t.Bool,
Since the configuration knob is moved to the scaling groups, let's remove this field.

2022-11-26 13:05 UTC, adrysn approved these changes
LGTM.

2022-11-26 13:26 UTC, merged