fix: logical errors in calculating monthly stats
lablup/backend.ai pull request #840
Opened 2022-10-26 09:14 UTC by Sujin-Kim1

this resolves #839

2022-11-01 04:23 UTC, fregataa requested changes
Let's replace `while` to `for ... in` statement

2022-11-01 04:23 UTC, fregataa commented on src/ai/backend/manager/api/resource.py
> +                    disk_used += int(nmget(last_stat, "io_scratch_size/stats.max", 0, "/"))
```suggestion
        for row in rows:
            if ts + time_window <= row.created_at.timestamp() or ts >= row.terminated_at.timestamp():
                continue
            num_sessions += 1
            cpu_allocated += int(row.occupied_slots.get("cpu", 0))
            mem_allocated += int(row.occupied_slots.get("mem", 0))
            if "cuda.devices" in row.occupied_slots:
                gpu_allocated += int(row.occupied_slots["cuda.devices"])
            if "cuda.shares" in row.occupied_slots:
                gpu_allocated += Decimal(row.occupied_slots["cuda.shares"])
            raw_stat = await redis_helper.execute(
                root_ctx.redis_stat, lambda r: r.get(str(row["id"]))
            )
            if raw_stat:
                last_stat = msgpack.unpackb(raw_stat)
                io_read_bytes += int(nmget(last_stat, "io_read.current", 0))
                io_write_bytes += int(nmget(last_stat, "io_write.current", 0))
                disk_used += int(nmget(last_stat, "io_scratch_size/stats.max", 0, "/"))
```
We can simply iterate the rows.

2022-11-01 05:38 UTC, Sujin-Kim1 commented on src/ai/backend/manager/api/resource.py
> +                    disk_used += int(nmget(last_stat, "io_scratch_size/stats.max", 0, "/"))
reflected! thanks :)

2022-11-03 03:17 UTC, fregataa approved these changes
lgtm

2022-11-03 08:17 UTC, merged