feat: implement `container_pid_to_host_pid()`
lablup/backend.ai pull request #955
Opened 2023-01-05 09:15 UTC by kyujin-cho

This PR implements `ai.backend.agent.utils.container_pid_to_host_pid()` function, which has been left as TODO.

2023-02-23 05:04 UTC, achimnol requested changes

2023-02-23 05:04 UTC, achimnol commented on src/ai/backend/agent/utils.py
> +                print(type(e), e)
Remove a debug print.

2023-02-23 05:04 UTC, achimnol commented on src/ai/backend/agent/utils.py
> +                print(type(e), e)
Same here. :wink:

2023-02-27 05:44 UTC, sanxiyn commented
This PR needs an update for cgroup v2 support(#865).

2023-06-10 05:58 UTC, achimnol approved these changes
It's a good refactoring.

Though, `get_conatiner_process_table()` could be reimplemented using `/proc/{pid}/status`'s `NSPid` field (ref: https://man7.org/linux/man-pages/man5/proc.5.html) following `get_host_process_table()`, as long as we're on the Linux kernel 4.1 or later.
I think we could rewrite `get_container_process_table()` as a follow-up PR.

2023-06-10 06:10 UTC, merged