feat: session based usage stats for given period
lablup/backend.ai pull request #962
Opened 2023-01-09 05:04 UTC by agatha197

resolves #961 
related PR: https://github.com/lablup/backend.ai-control-panel/pull/473

- `g_name` -> `g_group_name`  for clarity.
- `get_stats_for_period`
  - return usage statistics of sessions used within a given time period, group_ids, aggregated by group id.
  - [{domain_name: ..., g_infos: [s_infos: <result of `get_session_stats_for_period`>, ...]}, {...}]

- `get_session_stats_for_period`
  - return usage statistics of sessions used within a given time period, group_ids. 
  - [{id: '...', session_id: '...', c_infos: <result of `get_container_stats_by_session_id`>}, {...}]
  
- `get_container_stats_by_session_id`
  - return usage statistics for containers within a specific session.
  - [{id: '...', container_id: '...', ...}, {...}]

2023-01-19 07:48 UTC, fregataa reviewed
This work seems related to #963, which change name "group" to "project" in manager and
strongly related to #576, which divide kernel table and session table.
Plus, how about implementing a dataclass or attrs class for stats?
I would do this job if you do not mind.

2023-01-19 07:48 UTC, fregataa commented on src/ai/backend/manager/api/resource.py
> +async def get_stats_for_period(request: web.Request, start_date, end_date, group_ids=None):
It would be good to relocate this function to session table of model layer.
At least, we can locate them in kernel table.

2023-03-14 00:45 UTC, achimnol requested changes
If you replace existing codes, please remove them.
Or, apply proper refactor/fix to existing codes.

2023-03-14 00:45 UTC, achimnol commented on src/ai/backend/manager/models/kernel.py
> +from dateutil.tz.tz import tzfile
This could be merged to the above line.  Maybe your editor got confused about nested imports. :wink:
`from dateutil.tz import tzfile, tzutc`

2023-10-04 05:45 UTC, kyujin-cho approved these changes

2023-10-04 06:09 UTC, merged